#!/bin/bash
# SFTPxy Linux Installation Script
# This script installs SFTPxy as a systemd service.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

BINARY_SOURCE="$REPO_ROOT/bin/sftpxy"
WEB_DIST_SOURCE="$REPO_ROOT/web/dist"
MIGRATIONS_SOURCE="$REPO_ROOT/migrations"

BINARY_PATH="/usr/local/bin/sftpxy"
SHARE_DIR="/usr/local/share/sftpxy"
CONFIG_DIR="/etc/sftpxy"
CERT_DIR="$CONFIG_DIR/certs"
DATA_DIR="/var/lib/sftpxy"
LOG_DIR="/var/log/sftpxy"
SERVICE_FILE="/etc/systemd/system/sftpxy.service"
HOST_KEY_PATH="$DATA_DIR/keys/ssh_host_ed25519_key"
TLS_CERT_PATH="$CERT_DIR/sftpxy.crt"
TLS_KEY_PATH="$CERT_DIR/sftpxy.key"

generate_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
        return
    fi
    od -An -N32 -tx1 /dev/urandom | tr -d ' \n'
}

echo "=== SFTPxy Installation ==="

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root (sudo)"
    exit 1
fi

if [ ! -f "$BINARY_SOURCE" ]; then
    echo "Binary not found at $BINARY_SOURCE"
    echo "Please build first with: make build"
    exit 1
fi

if [ ! -d "$MIGRATIONS_SOURCE" ]; then
    echo "Migrations directory not found at $MIGRATIONS_SOURCE"
    exit 1
fi

if ! id -u sftpxy >/dev/null 2>&1; then
    echo "Creating sftpxy system user..."
    useradd --system --no-create-home --shell /usr/sbin/nologin sftpxy
fi

echo "Creating directories..."
mkdir -p \
    "$CONFIG_DIR" \
    "$CERT_DIR" \
    "$DATA_DIR/tmp" \
    "$DATA_DIR/plugins" \
    "$DATA_DIR/keys" \
    "$LOG_DIR" \
    "$SHARE_DIR"
chown -R sftpxy:sftpxy "$DATA_DIR" "$LOG_DIR"
chown -R root:sftpxy "$CONFIG_DIR"
chmod 750 "$DATA_DIR" "$LOG_DIR"
chmod 750 "$CONFIG_DIR" "$CERT_DIR"

echo "Installing binary..."
install -m 755 "$BINARY_SOURCE" "$BINARY_PATH"
chown root:root "$BINARY_PATH"

if [[ -n "${SFTPXY_TLS_CERT_FILE:-}" || -n "${SFTPXY_TLS_KEY_FILE:-}" ]]; then
    if [[ -z "${SFTPXY_TLS_CERT_FILE:-}" || -z "${SFTPXY_TLS_KEY_FILE:-}" ]]; then
        echo "Both SFTPXY_TLS_CERT_FILE and SFTPXY_TLS_KEY_FILE must be set together"
        exit 1
    fi
    if [[ ! -f "${SFTPXY_TLS_CERT_FILE}" || ! -f "${SFTPXY_TLS_KEY_FILE}" ]]; then
        echo "Provided TLS certificate files do not exist"
        exit 1
    fi
    echo "Installing TLS certificate bundle..."
    install -m 640 "${SFTPXY_TLS_CERT_FILE}" "$TLS_CERT_PATH"
    install -m 640 "${SFTPXY_TLS_KEY_FILE}" "$TLS_KEY_PATH"
    chown root:sftpxy "$TLS_CERT_PATH" "$TLS_KEY_PATH"
fi

if [[ ! -f "$TLS_CERT_PATH" || ! -f "$TLS_KEY_PATH" ]]; then
    echo "Production TLS certificate bundle not found."
    echo "Provide SFTPXY_TLS_CERT_FILE and SFTPXY_TLS_KEY_FILE before installation,"
    echo "or place certs at $TLS_CERT_PATH and $TLS_KEY_PATH."
    exit 1
fi

if [[ ! -f "$HOST_KEY_PATH" ]]; then
    echo "Generating persistent SSH host key..."
    "$BINARY_PATH" generate-hostkey --output "$HOST_KEY_PATH"
fi
chown sftpxy:sftpxy "$HOST_KEY_PATH"
chmod 600 "$HOST_KEY_PATH"

echo "Installing runtime resources..."
rm -rf "$SHARE_DIR/migrations"
cp -R "$REPO_ROOT/migrations" "$SHARE_DIR/migrations"
if [ -d "$WEB_DIST_SOURCE" ]; then
    mkdir -p "$SHARE_DIR/web"
    rm -rf "$SHARE_DIR/web/dist"
    cp -R "$REPO_ROOT/web/dist" "$SHARE_DIR/web/dist"
else
    echo "Warning: web/dist not found; HTTP static assets will not be installed"
fi
chown -R root:root "$SHARE_DIR"
chmod -R a+rX "$SHARE_DIR"

if [ ! -f "$CONFIG_DIR/config.yaml" ]; then
    echo "Generating deployment configuration..."
    SESSION_SECRET="$(generate_secret)"
    cat > "$CONFIG_DIR/config.yaml" <<EOF
# Generated by deploy/systemd/install.sh
common:
  service_name: "sftpxy"
  log_level: "info"
  log_path: "/var/log/sftpxy/sftpxy.log"
  temp_dir: "/var/lib/sftpxy/tmp"
  plugin_path: "/var/lib/sftpxy/plugins"
  global_timeout: 300

ssh:
  enabled: true
  listen_address: "0.0.0.0"
  listen_port: 30082
  host_keys:
    - "$HOST_KEY_PATH"
  password_auth: true
  public_key_auth: true
  certificate_auth: false
  max_connections: 100
  login_timeout: 60
  idle_timeout: 300
  scp_enabled: true
  banner: "Welcome to SFTPxy"
  allowed_algorithms: []
  disabled_algorithms: []

ftp:
  enabled: false
  listen_address: "0.0.0.0"
  listen_port: 30086
  explicit_tls: true
  tls_cert_file: "$TLS_CERT_PATH"
  tls_key_file: "$TLS_KEY_PATH"
  force_control_tls: true
  force_data_tls: true
  passive_port_start: 30100
  passive_port_end: 30199
  nat_external_address: ""
  max_connections: 50
  login_timeout: 60
  idle_timeout: 300

webdav:
  enabled: false
  listen_address: "0.0.0.0"
  listen_port: 30084
  base_path: "/"
  tls_cert_file: "$TLS_CERT_PATH"
  tls_key_file: "$TLS_KEY_PATH"
  client_cert: false

httpd:
  enabled: true
  listen_address: "0.0.0.0"
  listen_port: 30088
  client_listen_port: 30080
  tls_cert_file: "$TLS_CERT_PATH"
  tls_key_file: "$TLS_KEY_PATH"
  client_cert: false
  webadmin_enabled: true
  webclient_enabled: true
  rest_api_enabled: true
  openapi_enabled: true
  static_path: "/usr/local/share/sftpxy/web/dist"
  template_path: "/usr/local/share/sftpxy/web/dist"
  session_secret: "$SESSION_SECRET"
  token_expiry: 3600
  cors_origins:
    - "https://files.example.com"

data_provider:
  driver: "sqlite"
  connection_string: "/var/lib/sftpxy/sftpxy.db"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300
  auto_migrate: true

telemetry:
  enabled: true
  listen_address: "0.0.0.0"
  listen_port: 0
  tls_cert_file: ""
  tls_key_file: ""
  enable_profiling: false

http_clients:
  default_timeout: 30
  tls_verify: true
  max_connections: 100

commands:
  whitelist:
    - "/usr/local/bin/sftpxy-hook"
  timeout: 30

kms:
  type: "local"
  key_path: "/var/lib/sftpxy/keys/kms.key"

mfa:
  enabled: false
  issuer: "SFTPxy"
  force_for_admins: false
  force_for_users: false

smtp:
  host: "smtp.example.com"
  port: 587
  username: ""
  password: ""
  from: "noreply@example.com"
  use_tls: true

plugins:
  path: "/var/lib/sftpxy/plugins"
  enabled:
    ldap: false
    geoip: false
EOF
    chown root:sftpxy "$CONFIG_DIR/config.yaml"
    chmod 640 "$CONFIG_DIR/config.yaml"
else
    echo "Keeping existing configuration at $CONFIG_DIR/config.yaml"
fi

echo "Validating production configuration..."
"$BINARY_PATH" validate-config --config "$CONFIG_DIR/config.yaml" --strict-production

echo "Installing systemd service..."
install -m 644 "$REPO_ROOT/deploy/systemd/sftpxy.service" "$SERVICE_FILE"
systemctl daemon-reload

echo "Enabling and starting service..."
systemctl enable sftpxy
systemctl restart sftpxy

echo ""
echo "=== Installation Complete ==="
echo "Service status: $(systemctl is-active sftpxy)"
echo "Config file: $CONFIG_DIR/config.yaml"
echo "Data directory: $DATA_DIR"
echo "Log directory: $LOG_DIR"
echo "TLS certificate: $TLS_CERT_PATH"
echo "SSH host key: $HOST_KEY_PATH"
echo "Runtime resources: $SHARE_DIR"
echo ""
echo "Useful commands:"
echo "  systemctl status sftpxy    - Check service status"
echo "  systemctl restart sftpxy   - Restart service"
echo "  journalctl -u sftpxy -f    - View logs"
echo "  systemctl stop sftpxy      - Stop service"
echo "  printf 'StrongPassword' | $BINARY_PATH bootstrap-admin --config $CONFIG_DIR/config.yaml --username admin --password-stdin"
